### PR TITLE
Adding CircleCI and FeaturePeek

### PR DESCRIPTION
**Pull request by jasonbarry**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
🎉 Your [FeaturePeek environment](http://peek.run/l74hvj) is ready for your team to preview!

**Review by jasonbarry — COMMENTED** [review]
screenshot  looks good, but could you make the font size smaller?  {}

**Review by jasonbarry — COMMENTED** [review]
screenshot  damn straight  {}

**Review by jasonbarry — COMMENTED** [review]
screenshot  nice

**Review by jasonbarry — COMMENTED** [review]
screenshot  emoji ok?  
      <details>
        <summary>Browser metadata</summary>
        | Metadata | Value |
        |----------|-------------|
        | Path | /dns/ |
        | Viewport | 1280 x 714 |
        | Browser | Safari 12.0.3 |
        | OS | Mac OS 10.14.3 |
      </details>
      [View on FeaturePeek](http://localhost:3000/peek/4kghvp#/dns/)

**Review by jasonbarry — COMMENTED** [review]
screenshot  bloop  
      <details>
        <summary>Browser metadata</summary>
        Metadata | Value
        ---------|------------
        Path | /faq/
        Viewport | 1280 x 714
        Browser | Safari 12.0.3
        OS | Mac OS 10.14.3
      </details>
      [View on FeaturePeek](http://localhost:3000/peek/4kghvp#/faq/)

**Review by jasonbarry — COMMENTED** [review]
screenshot  idk  
      <details>
        <summary>Browser metadata</summary>
        <table>
          <tbody>
            <tr>
              <td>Path</td>
              <td>/faq/</td>
            </tr>
            <tr>
              <td>Browser</td>
              <td>Safari 12.0.3</td>
            </tr>
            <tr>
              <td>OS</td>
              <td>Mac OS 10.14.3</td>
            </tr>
            <tr>
              <td>Viewport</td>
              <td>1280 x 714</td>
            </tr>
          </tbody>
        </table>
      </details>
      [View on FeaturePeek](http://localhost:3000/peek/4kghvp#/faq/)

**Review by jasonbarry — COMMENTED** [review]
screenshot  tight  <details><summary>Browser metadata</summary>

    Path:      /
    Browser:   Safari 12.0.3
    OS:        Mac OS 10.14.3
    Viewport:  1280 x 714

</details>[View on FeaturePeek](http://localhost:3000/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
screenshot  boognish  <details><summary>Browser metadata</summary>

    Page URL:  /
     Browser:  Safari 12.0.3
          OS:  Mac OS 10.14.3
    Viewport:  1280 x 714

      </details>
      
      [View on FeaturePeek](http://localhost:3000/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
screenshot  that's cool  
<details><summary>Browser metadata</summary>

    Page URL:   /dns/
    Browser:    Safari 12.0.3 / Mac OS 10.14.3
    Viewport:   1280 x 714
    Screen DPI: 2x
    Language:   en-US
    Cookies:    Yes

</details>

[View on FeaturePeek](http://localhost:3000/peek/4kghvp#/dns/)

**Review by jasonbarry — COMMENTED** [review]
screenshot  awww yeahhh  
<details><summary>Browser metadata</summary>

    Page URL:      /dns/
    Browser:       Safari 12.0.3 / Mac OS 10.14.3
    Viewport:      1280 x 714
    Screen DPI:    2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/4kghvp#/dns/)

**Review by jasonbarry — COMMENTED** [review]
screenshot  canvasss

**Review by jasonbarry — COMMENTED** [review]
screenshot  

saving with metadata  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

🔗 [View on FeaturePeek](http://localhost:3000/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
testing  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
inline SVG chrome  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Chrome 74.0.3729.157 / Mac OS 10.14.5
    Viewport:      1280 x 698 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
svg?  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 356 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
hi eric  <details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1281 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
even more speed coming sooooon
<details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1281 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
hello world!
<details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Chrome 74.0.3729.169 / Mac OS 10.14.5
    Viewport:      1280 x 698 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by ghost — COMMENTED** [review]
**womohenico@max-mail.com says...**



one tap away huh
<details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by ghost — COMMENTED** [review]
**Womohenico says...**



boop
<details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1280 x 714 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
hello world!
<details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1284 x 688 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Review by jasonbarry — COMMENTED** [review]
love this!
<details><summary>Browser metadata</summary>

    Page path:     /
    Browser:       Safari 12.1.1 / Mac OS 10.14.5
    Viewport:      1018 x 679 @2x
    Language:      en-US
    Cookies:       Yes

</details>

[View on FeaturePeek](https://dashboard.dev.featurepeek.com/peek/4kghvp#/)

**Pull request closed without merging**
